language: rust

cache: cargo

env:
  - RUSTFLAGS='-D warnings'

rust:
  - stable
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allowed_failures:
    - rust: nightly

script:
  - rustup component add clippy
  - cargo test --all --all-features
  - cargo test --all --all-features --release
  - cargo clippy

deploy:
  provider: cargo
  token: "${CRATES_IO_TOKEN}"
  on:
    tags: true
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable && $TRAVIS_OS_NAME = linux

notifications:
  email:
    on_success: never
